---
version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
    allow:
      - dependency-type: "all"
    groups:
      cargo-deps:
        patterns:
          - "*"
    assignees:
      - b-n
