[build]
target = "index.html"
dist = "dist"

[[hooks]]
# Execute the custom asset pipeline for recipes and other assets
stage = "build"
command = "bin/nom-nom-assets"
# Use the following lines instead to debug the asset pipeline
#command = "cargo"
#command_arguments = ["run", "--release", "-p", "nom-nom-assets"]

[watch]
ignore = [".cache/"]

[serve]
# Serve on the current IP address too instead of just localhost
address = "0.0.0.0"
port = 8080
