version: 2

aliases:
  - &docker
    - image: circleci/node:12.16.3
  - &restore_cache
    restore_cache:
      keys:
        - v1-yarn-pkgs-{{ checksum "yarn.lock" }}
  - &save_cache
    save_cache:
      key: v1-yarn-pkgs-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn
  - &install
    run:
      name: Yarn
      command: yarn install --immutable
  - &attach_workspace
    at: .

jobs:
  setup:
    docker: *docker
    steps:
      - checkout
      - *restore_cache
      - *install
      - *save_cache
  lint:
    docker: *docker
    steps:
      - checkout
      - *restore_cache
      - *install
      - run:
         name: lint
         command: yarn run lint
  build:
    docker: *docker
    steps:
      - checkout
      - *restore_cache
      - *install
      - run:
          name: build
          command: yarn run build
      - persist_to_workspace:
          root: .
          paths:
            - public
  deploy:
    docker: *docker
    steps:
      - checkout
      - attach_workspace: *attach_workspace
      - *restore_cache
      - *install
      - run:
          name: vars
          command: |
            git config user.name $GH_NAME
            git config user.email $GH_EMAIL
      - run:
          name: deploy
          command: yarn run deploy
workflows:
  version: 2
  commit:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - setup
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - lint
            - build
