[package]
name = "nom-nom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "parse_data"

[dependencies]
yew = { version = "0.20.0", features = ['csr'] }
yew-hooks = "0.2.0"
rust-i18n = "2"
stylist = { version = "0.11", features = ['yew_use_style', 'parser'] }
pulldown-cmark = "0.9.3"
