[build]
target = "index.html"
dist = "dist"

[[hooks]]
# Execute the custom asset pipeline for recipes and other assets
stage = "build"
command = "cargo"
command_arguments = ["run", "-p", "asset-pipeline"]
